name: just_breathe
description: A simple mediation app

version: 1.0.0+3

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  flutter_riverpod: ^0.11.1
  google_fonts: ^1.0.0
  styled_widget: ^0.2.1+2
  flutter_icons: ^1.1.0
  url_launcher: ^5.4.5
  responsive_framework: ^0.0.4
  assets_audio_player: ^1.3.8
  tinycolor: ^1.0.2
  copy_with_extension: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  intl_translation: ^0.17.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  copy_with_extension_gen: ">=1.0.0 <2.0.0"



flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - google_fonts/
flutter_intl:
  enabled: true
